---
- name: "Install python-module"
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - python-pip
  - python-pexpect

- name: "Upgrade pip"
  pip:
    name: pip
    extra_args: "--upgrade"

- name: "Install docker-py"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-py
    - python-gitlab

- name: "Deploy init-ptoken.py"
  template:
    src: "{{ item }}.j2"
    dest: "/root/{{ item }}"
    owner: "{{ gitlab_user }}"
    group: "{{ gitlab_group }}"
    mode: 0755
  with_items:
  - init-ptoken.py

- name: "Initialize Private Token script"
  shell: "python /root/init-ptoken.py"

- name: "Digest secret key"
  shell: "cat /tmp/secret.txt && rm -f /tmp/secret.txt"
  register: ptoken

- set_fact:
    gitlab_token: "{{ ptoken.stdout_lines | join(' ')}}"

- name: "Deploy Gitlab cfg"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
  with_items:
  - python-gitlab.cfg

- name: "Create projects"
  shell: "gitlab -g gitlab project create --name {{ item.name }}"
  with_items:
  - "{{ external_code }}"

- name: "Reconfigure origin ref"
  shell: "cd {{ gitlab_code_dir }}{{ item.path }}/{{ item.name }} && \
          git remote rm origin && \
          git remote add origin ssh://git@{{ gitlab_hostname }}:{{ gitlab_ssh }}/root/{{ item.name }}.git"
  with_items:
  - "{{ external_code }}"

- name: "Push code"
  expect:
    command: "git push origin master"
    chdir: "{{ gitlab_code_dir }}{{ item.path }}/{{ item.name }}"
    responses:
      (?i)fingerprint: "yes"
  with_items:
  - "{{ external_code }}"

  ## TODO FIX static external code list variable.
